[local-server]
name = "alph"
timestamp = 2019-11-19T21:49:11.000000
cache-dir = "/var/cache/zhsm"
temp-dir = "/tmp/zhsm"
my-network = "home"
targets = { home = "192.168.0.100", buckelw = "192.168.3.100" }

# specify the postgres database connect params
postgres = "host=192.168.0.99 user=... password=... dbname=... port=..."

[ctrlserver]
id = 0
scripts-dir = "/opt/zhsm-scripts"

[[servers]]
name = "bongo"
uuid = "...."
# address should be reachable by the local ctrlserver
# if not given, use targets[dbserver.my-network]
# address = ...
# routing from buckelw to bongo via the ctrlserver
targets = { home = "192.168.0.101" }
serve = ["fs"]

[fileserver.backends.a]
path = "/mnt/sda1"
uuid = "550e8400-e29b-41d4-a716-446655450110"
